site_name: Who am I
site_author: Rafi Darmawan
site_url: https://drmwnrafi.github.io/protofolio/

theme:
  name : material
  logo : assets/media/ziczac.png
  favicon : assets/media/ziczac.png
  custom_dir: overrides
  features:
    - announce.dismiss
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: fontawesome/solid/moon 
        name: Switch to dark mode
      primary: white
      accent: deep orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: fontawesome/solid/sun 
        name: Switch to light mode    
      primary: black
      accent: lime
  font:
      text: Montserrat

plugins:
  - social
  - search
  - autorefs

extra:
  extra_shadow_root_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css

  # generator: false

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.blocks.caption
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.superfences:
  #     custom_fences:
        # - name: mermaid
        #   class: mermaid
        #   format: !!python/name:mermaid2.fence_mermaid_custom

extra_javascript:
  - assets/js/mathjax-config.js
  - assets/js/card.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - assets/css/extra.css
  - assets/css/card.css
#   - https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

nav :
  - index.md
  - Robotics : robotics.md
  - AI : ai.md